[package]
name = "tetsy-wordlist"
version = "1.2.0"
description = "Word list used to generate brain wallets for Tetsy."
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
lazy_static = "0.2"
rand = "0.3"
itertools = "0.5"
